version: "3"
services:
  server:
    image: drone/drone:1
    ports:
      - 80:80
      - 443:443
    environment:
      DRONE_GITHUB_CLIENT_ID: ${DRONE_GITHUB_CLIENT_ID}
      DRONE_GITHUB_CLIENT_SECRET: ${DRONE_GITHUB_CLIENT_SECRET}
      DRONE_RPC_SECRET: ${DRONE_RPC_SECRET}
      DRONE_SERVER_HOST: ${DRONE_SERVER_HOST}
      DRONE_SERVER_PROTO: ${DRONE_SERVER_PROTO}
    restart: always
    volumes:
      - /private/var/lib/drone:/data
  docker_runner:
    image: drone/drone-runner-docker:1
    environment:
      DRONE_RPC_SECRET: ${DRONE_RPC_SECRET}
      DRONE_RPC_HOST: ${DRONE_RPC_HOST}
      DRONE_RPC_PROTO: ${DRONE_RPC_PROTO}
      DRONE_RUNNER_CAPACITY: ${DRONE_RUNNER_CAPACITY}
      DRONE_RUNNER_NAME: ${HOSTNAME}
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock